
        // Automatically generated file. Do not edit.
        
        package pulpcore;
        
        /**
            The Build class provides information on this build of PulpCore.
            This class is automatically generated by the Ant build file.
        */
        public interface Build {
        
            /** The version number of this PulpCore build. */
            public static final String VERSION = "0.11.4";
            
            /** The build date. */
            public static final String BUILD_DATE = "2008/12/12 08:14:04";
            
            /** The platform name of this PulpCore build. */
            public static final String PLATFORM = "desktop";
            
            /** 
                The debug flag of this PulpCore build. If DEBUG is true:
                <ul>
                <li>Press ctrl-C to view the console. The console also appears when 
                there is an uncaught exception.</li>
                <li>Press ctrl-I to view frame rate and memory information.</li>
                <li>Press ctrl-D to view dirty rectangles (Scene2D only).</li>
                </ul>
            */
            public static final boolean DEBUG = true;
            
        }
        
        
